# root for extending
resources:
  repositories:
    - repository: this
      type: github
      name: PrickettAcademy/Simple
      endpoint: mygh

jobs:
- deployment: one
  pool: default
  environment: PROD
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo root yml file
        - checkout: this
