# base 2 for extending
resources:
  repositories:
    - repository: this
      type: github
      name: PrickettAcademy/Simple
      endpoint: mygh

jobs:
- deployment: one
  pool: default
  environment: PROD
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo Using PROD env from base-deployment-2
        - checkout: this
